[build]
  functions = "netlify/functions"
  publish = "."

[[redirects]]
  from = "/api/history"
  to = "/.netlify/functions/history"
  status = 200

[[redirects]]
  from = "/api/alerts"
  to = "/.netlify/functions/alerts"
  status = 200
